version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: phn_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "P@kwt142005"
      MYSQL_DATABASE: "qlchoto"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
